AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'bin/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false