AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'db/**/*.rb'
    - 'bin/*'
  NewCops: disable

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LineLength:
  Max: 200
  Exclude:
    - 'spec/factories/*.rb'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
